[[mutation]]
source_file = "block/blk-core.c"
definition_source_file = "block/blk.h"
sed_pattern = "s|#define BLK_MAX_REQUEST_COUNT\\t32|#define BLK_MAX_REQUEST_COUNT\\t16|"

[[mutation]]
source_file = "block/blk-mq.c"
definition_source_file = "block/blk.h"
sed_pattern = "s|#define BLK_MAX_REQUEST_COUNT\\t32|#define BLK_MAX_REQUEST_COUNT\\t16|"
