[[mutation]]
source_file = "block/bfq-iosched.c"
definition_source_file = "block/bfq-iosched.c"
sed_pattern = "s|static const int bfq_default_max_budget = 16 \\* 1024;|static const int bfq_default_max_budget \\= 32 \\* 1024;|"
