[[mutation]]
source_file = "net/ipv4/tcp_output.c"
definition_source_file = "include/net/tcp.h"
sed_pattern = "s|#define TCP_TIMEOUT_MIN_US (2\\*USEC_PER_MSEC)|#define TCP_TIMEOUT_MIN_US 10|"

[[mutation]]
source_file = "net/ipv4/tcp_recovery.c"
definition_source_file = "include/net/tcp.h"
sed_pattern = "s|#define TCP_TIMEOUT_MIN_US (2\\*USEC_PER_MSEC)|#define TCP_TIMEOUT_MIN_US 10|"
